service: simple-http-endpoint

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  stackName: simple-http-api-${self:provider.stage}

functions:
  simpleHttpApi:
    handler: handler.handler
    description: Simple HTTP API example
    timeout: 240
